import requests
import json

def test_get_embeddings():
    url = "http://127.0.0.1:5000/get_embeddings"
    headers = {
        'Content-Type': 'application/json'
    }
    data = {
        'protein_sequences': [
            'MKKKYILAIDQGTTSSRAILFDHKGRIIGMAQREFTQIFPQPGWVEHNPRDIMTSVYTTITELLNNTQIDVRAIAGIGITNQRETTVIWDRQTGQPIYNAIVWQSRQTKDICDQLTTAGYQDMVHAKTGLLIDAYFSGTKVKWILDHVENAHTQAARGELAFGTIDTWIIWNLTGGQVHVTDYSNASRTLLYDIHALRWDPDLLTMLDIPAAILPDVRSSSEIYGLTQTPYFHGEQIPIAGIAGDQQAALFGQACFEPGMAKNTYGTGCFMLMHTGKKAVESQNGLLTTIAWGLNGEIEYALEGSIFIAGSVVQWLRDGLRMFGKASDSQAYADRVSDNGGVYVVPAFVGLGAPYWRSDVRGAVFGLTRSTTKEHFVRAALESMAYQTRDVLSAMQADADIELKELRTDGAAITNDFMAQFQSDILAVPVLRSQIAETTALGAAYLAGLATGFWSSREEMTQHWAINRCFKPQMDKEQREHLYAGWKQAVEATLGFRVA',
            'TTITELLNNTQIDVRAIAGIGAIVWQSRQTKDICDQLTTAGYQDMVHATWIIWNLTGGQVHVTDYSNASRTLLYDIHALRWDPDLLTMLHGEQIPIAGIAGDQQAALFGQACFEPGMAKNTYGTGCFMLMHTGKKAVESQNGLLTTIAWGLNGEIEYALEGSIFIAGSVVQWLRDGLRMFGKASDSQAYADRVSDNGGVYVVPAFVGLGAPYWRSDVRGAVFGLTRSTTKEHFVRAALESMAYQTRDVLSAMQADADIELKELRTDGAAITNDFMAQFQSDILAVPVLRSQIAETTALGAAYLAGLATGFWSSREEMTQHWAINRCFKPQMDKEQREHLYAGWKQAVEATLGFRVA'
        ]
    }
    response = requests.post(url, headers=headers, data=json.dumps(data))
    assert response.status_code == 200
    response_data = response.json()
    assert 'embeddings' in response_data  # Updated key to 'embeddings'
    print("Test passed!")

if __name__ == '__main__':
    test_get_embeddings()
