# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: train large models

target:
  service: amlk8s
  name: itplabrr1cl1
  vc: mprr2

environment:
  image: azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04:latest # ex: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  conda_yaml_file: $CONFIG_DIR/environment.yml

code:
  local_dir: $CONFIG_DIR/ 

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
# - name: '{zero shot}{large MLP}{default}{esm-2}{label noise 10}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
#     --name '{zero shot}{large MLP}{default}{esm-2}{label noise 10}'
#     --override SEQUENCE_ENCODER_IDENTIFIER esm-2 PROTEIN_EMBEDDING_DIM 320 LABEL_EMBEDDING_NOISING_ALPHA 10 NUM_EPOCHS 64 LABEL_EMBEDDING_POOLING_METHOD mean EXTRACT_VOCABULARIES_FROM null OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 3 OUTPUT_MLP_NUM_LAYERS 3 PROJECTION_HEAD_NUM_LAYERS 4 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{large MLP}{default}{esm-2}{label noise 20}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
#     --name '{zero shot}{large MLP}{default}{esm-2}{label noise 20}'
#     --override SEQUENCE_ENCODER_IDENTIFIER esm-2 PROTEIN_EMBEDDING_DIM 320 LABEL_EMBEDDING_NOISING_ALPHA 20 NUM_EPOCHS 64 LABEL_EMBEDDING_POOLING_METHOD mean EXTRACT_VOCABULARIES_FROM null OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 3 OUTPUT_MLP_NUM_LAYERS 3 PROJECTION_HEAD_NUM_LAYERS 4 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero shot}{large MLP}{default}{proteinfer}{label noise 40}'
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py 
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
    --name '{zero shot}{large MLP}{default}{proteinfer}{label noise 40}'
    --override LABEL_EMBEDDING_NOISING_ALPHA 40 NUM_EPOCHS 32 LABEL_EMBEDDING_POOLING_METHOD mean EXTRACT_VOCABULARIES_FROM null OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 3 OUTPUT_MLP_NUM_LAYERS 3 PROJECTION_HEAD_NUM_LAYERS 4 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 4
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{medium MLP}{default}{esm-2}{label noise 10}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH 
#     --validation-path-name VAL_DATA_PATH 
#     --test-paths-names TEST_DATA_PATH 
#     --full-path-name FULL_DATA_PATH
#     --name '{normal}{medium MLP}{default}{esm-2}{label noise 10}'
#     --override LABEL_EMBEDDING_NOISING_ALPHA 10 SEQUENCE_ENCODER_IDENTIFIER esm-2 PROTEIN_EMBEDDING_DIM 320
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{large MLP}{default}{esm-2}{label noise 0}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH 
#     --validation-path-name VAL_DATA_PATH 
#     --test-paths-names TEST_DATA_PATH 
#     --full-path-name FULL_DATA_PATH
#     --name '{normal}{large MLP}{default}{esm-2}{label noise 0}'
#     --override LABEL_EMBEDDING_NOISING_ALPHA 0 SEQUENCE_ENCODER_IDENTIFIER esm-2 PROTEIN_EMBEDDING_DIM 320 OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 3 OUTPUT_MLP_NUM_LAYERS 3 PROJECTION_HEAD_NUM_LAYERS 4 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 4
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{large MLP}{names}{mean}{sequence augmentations 0.1}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH 
#     --validation-path-name VAL_DATA_PATH 
#     --test-paths-names TEST_DATA_PATH 
#     --full-path-name FULL_DATA_PATH
#     --name '{normal}{large MLP}{names}{mean}{sequence augmentations 0.1}'
#     --override NUM_EPOCHS 64 LABEL_EMBEDDING_POOLING_METHOD mean EXTRACT_VOCABULARIES_FROM FULL_DATA_PATH OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 3 OUTPUT_MLP_NUM_LAYERS 3 PROJECTION_HEAD_NUM_LAYERS 4 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{medium MLP}{names}{mean}{sequence augmentations 0.1}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH 
#     --validation-path-name VAL_DATA_PATH 
#     --test-paths-names TEST_DATA_PATH 
#     --full-path-name FULL_DATA_PATH
#     --name '{normal}{medium MLP}{names}{mean}{sequence augmentations 0.1}'
#     --override NUM_EPOCHS 64 LABEL_EMBEDDING_POOLING_METHOD mean EXTRACT_VOCABULARIES_FROM FULL_DATA_PATH OUTPUT_MLP_HIDDEN_DIM_SCALE_FACTOR 2 OUTPUT_MLP_NUM_LAYERS 2 PROJECTION_HEAD_NUM_LAYERS 2 PROJECTION_HEAD_HIDDEN_DIM_SCALE_FACTOR 2
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 10}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 10}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_NOISING_ALPHA 10 
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{proteinfer}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
#     --name '{zero shot}{medium MLP}{proteinfer}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_NOISING_ALPHA 0 SEQUENCE_ENCODER_IDENTIFIER proteinfer
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{esm-2}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py 
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT 
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT 
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT 
#     --name '{zero shot}{medium MLP}{esm-2}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_NOISING_ALPHA 0 SEQUENCE_ENCODER_IDENTIFIER esm-2 PROTEIN_EMBEDDING_DIM 320
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"