# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: Testing augmentation with synonyms normal+zero_shot #Normal training with augmentations part2 v3

target:
  service: sing
  name: barlow01
  workspace_name: msrresrchws
environment:
  image: amlt-sing/acpt-2.0.1-py3.10-cuda11.8 #azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04:latest 
  conda_yaml_file: $CONFIG_DIR/environment.yml
  skip_conda_packages_on_sing:
  - tensorflow
  - cudatoolkit
  - deepspeed
  - pip
  - python\b


code:
  local_dir: $CONFIG_DIR/ 

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
# - name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}{weighted_sampling False}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}{weighted_sampling False}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label WEIGHTED_SAMPLING False
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}{loss_fn BCE}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}{loss_fn BCE}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label LOSS_FN BCE
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder biogpt}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder biogpt}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT microsoft/biogpt AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder E5_multiling_inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder E5_multiling_inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 0 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0}{label_noise 20}{label_encoder E5_multiling_inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0}{label_noise 20}{label_encoder E5_multiling_inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0 LABEL_EMBEDDING_NOISING_ALPHA 20 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"


















- name: '{normal_clustered}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
  sku: G8-V100
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_CLUSTERED_DATA_PATH
    --validation-path-name VAL_CLUSTERED_DATA_PATH
    --name '{normal_clustered}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
    --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 100 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_BASE_URL: "https://microsoft-research.wandb.io"
      WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names+label}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 100 LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#     --load-model 'models/ProTCL/normal_test_label_aug_v4.pt'
#     --from-checkpoint
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{normal}{MLP Large}{descriptions names+label+synonyms}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names+label+synonyms}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 100 LABEL_AUGMENTATION_DESCRIPTIONS name+label+synonym_exact INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero_shot}{MLP Large}{descriptions names+label+synonyms}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}'
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --name '{zero_shot}{MLP Large}{descriptions names+label+synonyms}{ensemble True}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}'
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 LABEL_AUGMENTATION_DESCRIPTIONS name+label+synonym_exact INFERENCE_GO_DESCRIPTIONS name+label
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"













# - name: '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --test-paths-names TEST_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling_inst}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 64
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"

# - name: '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling_inst}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --test-paths-names TEST_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling_inst}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 10 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 64
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"

# - name: '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder E5_multiling_inst}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --test-paths-names TEST_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder E5_multiling_inst}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 0 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 64
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"

# - name: '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder biogpt}' 
#   sku: G8-V100
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --test-paths-names TEST_DATA_PATH
#     --name '{normal}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 0}{label_encoder biogpt}' 
#     --override ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT microsoft/biogpt AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 0 VALIDATION_BATCH_SIZE 8 TEST_BATCH_SIZE 8 NUM_EPOCHS 64
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_BASE_URL: "https://microsoft-research.wandb.io"
#       WANDB_API_KEY: "$WANDB_API_KEY"







  