# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: Zero shot ablations. label noise + label augmentation #test regularization strategies for zero shot

target:
  service: amlk8s
  name: itplabrr1cl1
  vc: mprr2

environment:
  image: azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04:latest # ex: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  conda_yaml_file: $CONFIG_DIR/environment.yml

code:
  local_dir: $CONFIG_DIR/ 

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
- name: '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 20}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 20
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 30
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 40}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions names}{pooling mean}{sequence_augmentations 0.1}{label_noise 40}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 40
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"




- name: '{zero_shot}{MLP Large}{descriptions names+label}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions name+label}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 30  LABEL_AUGMENTATION_DESCRIPTIONS name+label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero_shot}{MLP Large}{descriptions names+label}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions names+label}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 10  LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"



- name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble true}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions name+label}{ensemble true}{pooling mean}{sequence_augmentations 0.1}{label_noise 30}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 30  LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero_shot}{MLP Large}{descriptions names+label}{ensemble true}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero_shot}{MLP Large}{descriptions names+label}{ensemble true}{pooling mean}{sequence_augmentations 0.1}{label_noise 10}{label_encoder E5_multiling inst}' 
    --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1 LABEL_EMBEDDING_NOISING_ALPHA 10  LABEL_AUGMENTATION_DESCRIPTIONS name+label INFERENCE_GO_DESCRIPTIONS name+label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{BioGPT}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{BioGPT}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro AUGMENT_RESIDUE_PROBABILITY 0
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{E5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{E5}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/e5-large-v2 AUGMENT_RESIDUE_PROBABILITY 0
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{E5 multiling inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0}{label noise 0}{E5 multiling inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"


# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{BioGPT}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{BioGPT}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro AUGMENT_RESIDUE_PROBABILITY 0.1
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/e5-large-v2 AUGMENT_RESIDUE_PROBABILITY 0.1
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5 multiling inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5 multiling inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.1
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"




# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{BioGPT}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{BioGPT}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro AUGMENT_RESIDUE_PROBABILITY 0.2
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{E5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{E5}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/e5-large-v2 AUGMENT_RESIDUE_PROBABILITY 0.2
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{E5 multiling inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.2}{label noise 0}{E5 multiling inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.2
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"



  
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{BioGPT}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{BioGPT}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro AUGMENT_RESIDUE_PROBABILITY 0.3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{E5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{E5}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/e5-large-v2 AUGMENT_RESIDUE_PROBABILITY 0.3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{E5 multiling inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{Large MLP}{names}{mean}{sequence augmentations 0.3}{label noise 0}{E5 multiling inst}' 
#     --override EXTRACT_VOCABULARIES_FROM null ESTIMATE_MAP True OPTIMIZATION_METRIC_NAME f1_macro LABEL_ENCODER_CHECKPOINT intfloat/multilingual-e5-large-instruct AUGMENT_RESIDUE_PROBABILITY 0.3
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"