# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: Protein Functions Experiment

target:
  service: amlk8s
  name: itplabrr1cl1
  vc: mprr2

environment:
  image: azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04:latest # ex: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  conda_yaml_file: $CONFIG_DIR/environment.yml

code:
  local_dir: $CONFIG_DIR/ 

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
- name: AMLT-FL-70-1.75-0.9
  sku: G8
  priority: high
  command:
  - python main.py 
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH 
    --validation-path-name VAL_DATA_PATH 
    --test-paths-names TEST_DATA_PATH 
    --full-path-name FULL_DATA_PATH 
    --name AMLT-FL-70-1.75-0.9
    --override NUM_EPOCHS 70 FOCAL_LOSS_GAMMA 1.75 FOCAL_LOSS_ALPHA 0.9
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
