# For field details: https://amulet-docs.azurewebsites.net/config_file.html
description: Test E5 multilingual instruct label embeddings #test regularization strategies for zero shot

target:
  service: amlk8s
  name: itplabrr1cl1
  vc: mprr2

environment:
  image: azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04:latest # ex: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  conda_yaml_file: $CONFIG_DIR/environment.yml

code:
  local_dir: $CONFIG_DIR/ 

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"

# - name: '{normal}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --nodes 1
#     --gpus 8
#     --train-path-name TRAIN_DATA_PATH
#     --validation-path-name VAL_DATA_PATH
#     --test-paths-names TEST_DATA_PATH
#     --name '{normal}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}'
#     --override LABEL_EMBEDDING_POOLING_METHOD mean
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
- name: '{zero shot}{medium MLP}{labels}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
    --validation-path-name VAL_DATA_PATH_ZERO_SHOT
    --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
    --name '{zero shot}{medium MLP}{labels}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}'
    --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean LABEL_AUGMENTATION_DESCRIPTIONS label INFERENCE_GO_DESCRIPTIONS label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"

- name: '{normal}{medium MLP}{labels}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}' 
  sku: G8
  priority: high
  preemptible: False
  command:
  - python main.py
    --nodes 1
    --gpus 8
    --train-path-name TRAIN_DATA_PATH
    --validation-path-name VAL_DATA_PATH
    --test-paths-names TEST_DATA_PATH
    --name '{normal}{medium MLP}{labels}{mean}{sequence augmentations 0.1}{label noise 0}{E5_multiling_inst}'
    --override LABEL_EMBEDDING_POOLING_METHOD mean LABEL_AUGMENTATION_DESCRIPTIONS label INFERENCE_GO_DESCRIPTIONS label
    --amlt
    --use-wandb
  submit_args:
    env:
      WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{wDecay 0.001}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{wDecay 0.001}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean OPTIMIZER AdamW WEIGHT_DECAY 0.001
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{wDecay 0.01}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{wDecay 0.01}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean OPTIMIZER AdamW WEIGHT_DECAY 0.01
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{sequence dropout 0.5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{sequence dropout 0.5}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean SEQUENCE_EMBEDDING_DROPOUT 0.5 
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{sequence dropout 0.25}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{sequence dropout 0.25}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean SEQUENCE_EMBEDDING_DROPOUT 0.25 
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{label dropout 0.5}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{label dropout 0.5}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean LABEL_EMBEDDING_DROPOUT 0.5 
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
# - name: '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{label dropout 0.25}' 
#   sku: G8
#   priority: high
#   preemptible: False
#   command:
#   - python main.py
#     --train-path-name TRAIN_DATA_PATH_ZERO_SHOT
#     --validation-path-name VAL_DATA_PATH_ZERO_SHOT
#     --test-paths-names UNSEEN_DATA_PATH_ZERO_SHOT
#     --name '{zero shot}{medium MLP}{names}{mean}{sequence augmentations 0.1}{label noise 0}{label dropout 0.25}'
#     --override EXTRACT_VOCABULARIES_FROM null LABEL_EMBEDDING_POOLING_METHOD mean LABEL_EMBEDDING_DROPOUT 0.25 
#     --amlt
#     --use-wandb
#   submit_args:
#     env:
#       WANDB_API_KEY: "$WANDB_API_KEY"
