---
# Parameters for model training
#TODO: Optimizer can also be a hyperparameter
params:
  LEARNING_RATE: 0.0003
  TEMPERATURE: 0.1 #Not used right now b/c of new loss
  SYMMETRIC_LOSS: False
  PROTEIN_EMBEDDING_DIM: 1100
  LABEL_EMBEDDING_DIM: 1024
  LATENT_EMBEDDING_DIM: 1024
  OUTPUT_DIM: 1024
  OUTPUT_NUM_LAYERS: 2
  NUM_EPOCHS: 1
  TRAIN_BATCH_SIZE: 128
  VALIDATION_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  LABEL_BATCH_SIZE: 500
  VALIDATION_FREQUENCY: 500
  DECISION_TH: 0.92 # Set to null if you want to use the best threshold from validation
  NUM_WORKERS: 2
  TRAIN_SEQUENCE_ENCODER: False
  TRAIN_LABEL_ENCODER: False
  TRAIN_PROJECTION_HEAD: True
  NORMALIZE_PROBABILITIES: False
  SEED: 42
  NUM_LABELS: 32102
  GRADIENT_ACCUMULATION_STEPS: 1 # 1 is essentially no gradient accumulation
  LABEL_ENCODER_CHECKPOINT: microsoft/biogpt
  LABEL_SAMPLE_SIZE: 300
  LABEL_BATCH_SIZE_LIMIT: 300

#Constants for protein encoder model (e.g. ProteInfer). Not really params since 
# we are not going to change these.
embed_sequences_params:
  INPUT_CHANNELS: 20
  OUTPUT_CHANNELS: 1100
  KERNEL_SIZE: 9
  DILATION_BASE: 3
  NUM_RESNET_BLOCKS: 5
  BOTTLENECK_FACTOR: 0.5

# Paths to data, vocabularies, embeddings, and models
relative_paths:
  # ProteInfer data paths
  TRAIN_DATA_PATH: data/swissprot/proteinfer_splits/random/train_GO.fasta
  VAL_DATA_PATH: data/swissprot/proteinfer_splits/random/dev_GO.fasta
  TEST_DATA_PATH: data/swissprot/proteinfer_splits/random/test_GO.fasta
  FULL_DATA_PATH: data/swissprot/proteinfer_splits/random/full_GO.fasta

  # Zero shot data paths
  ZERO_SHOT_DATA_PATH: data/zero_shot/SwissProt_2023_unseen_sequences_and_labels.fasta

  # Vocabulary paths
  VOCABULARIES_DIR: data/vocabularies
  AMINO_ACID_VOCAB_PATH: data/vocabularies/amino_acid_vocab.json
  GO_LABEL_VOCAB_PATH: data/vocabularies/GO_label_vocab.json
  SEQUENCE_ID_VOCAB_PATH: data/vocabularies/sequence_id_vocab.json
  GO_ANNOTATIONS_PATH: data/annotations/go_annotations_2019_07_01.pkl

  # Embeddings paths (if using frozen pre-trained models)
  EMBEDDING_DIR: data/embeddings
  LABEL_EMBEDDING_PATH: data/embeddings/frozen_PubMedBERT_label_embeddings.pkl
  SEQUENCE_EMBEDDING_PATH: data/embeddings/frozen_proteinfer_sequence_embeddings.pkl
 
  # Where to save the model
  OUTPUT_MODEL_DIR: models/ProTCL

  # Where to save results
  RESULTS_DIR: results/

  PARENTHOOD_LIB_PATH: data/vocabularies/parenthood.json.gz
  PROTEINFER_WEIGHTS_PATH: 'models/proteinfer/GO_model_weights.pkl'